### ISSUE TITLE
Move contributing to end

### ISSUE THREAD

**Issue by cookieguru** [andrewwoods/php-in-seattle#13]
When viewing `companies.md` the very first thing presented is the contributing guidelines, rather than the list.  Since the list is the primary reason for viewing this file, would it be more appropriate to move this section to the end, or possibly a different file?

**Comment by andrewwoods** [comment]
@cookieguru I think we can remove it. There are plenty of examples now that one can follow, as opposed to when I started the project. If we do need some contributing information, I think it should be a separate markdown file.
